### ISSUE TITLE
Cant receive any notifications.

### ISSUE THREAD

**Issue by burjuyz** [kenneth-church/junction#1]
I've installed Juntion (docker) and Apprise-api (docker)
My config is
```
log-level: debug
port: 8025
junctions:
  - name: Telegram
    apprise: tgram://token/-chat/
    to:
      emails: telegram@mailrise.xyz
```

Log is 
```
6:41PM INF Listening on port 8025
6:41PM INF Email Received
6:41PM DBG To:[telegram@mailrise.xyz]
6:41PM DBG From:burjuy@local.nas
6:41PM DBG IP:192.168.10.200
6:41PM INF Sending notification to Junction - -1
6:41PM ERR Error with Apprise: exit status 1
6:41PM DBG 2023-06-19 18:41:59,542 - ERROR - There are no service(s) to notify

```

**Comment by kenneth-church** [comment]
It's not able to select your junction for some reason.

Can you try changing your config to
```
My config is

log-level: debug
port: 8025
junctions:
  - name: Telegram
    apprise: tgram://token/-chat/
    to:
      emails: 
        - telegram@mailrise.xyz
```

**Comment by burjuyz** [comment]
It doesn't help me

```
4:31PM DBG Log Level: debug
4:31PM INF Listening on port 8025
4:32PM INF Email Received
4:32PM DBG To:[telegram@mailrise.xyz]
4:32PM DBG From:burjuy@local.nas
4:32PM DBG IP:192.168.10.200
4:32PM INF Sending notification to Junction - -1
4:32PM ERR Error with Apprise: exit status 1
4:32PM DBG 2023-06-20 16:32:11,885 - ERROR - There are no service(s) to notify
```

**Comment by kenneth-church** [comment]
Hmm...
I'll get to debugging this. Does a wildcard rule pick up any emails?
```
log-level: debug
port: 8025
junctions:
  - name: Telegram
    apprise: tgram://token/-chat/
```
